name: 'Run Make Command'
description: 'run a make command'

inputs:
  command:
    description: 'The make command to run'
    required: true
  makefile:
    description: 'name of/path to Makefile (if not "Makefile")'
    required: false
    default: 'Makefile'

runs:
  using: 'composite'
  steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Display Environment Details
      shell: bash
      run: ls -latr

    - name: Prepare Environment
      shell: bash
      run: |
        echo "MAKEFILE=${{ inputs.makefile }}" >> $GITHUB_ENV
        echo "COMMAND=${{ inputs.command }}" >> $GITHUB_ENV

    - name: Run Make Command
      shell: bash
      run: ./run.sh
