name: "Run Make Command"
description: "A template action to run make commands "

inputs:
  command:
    description: 'The make command to run'
    required: true
  makefile:
    description: 'name of/path to Makefile (if not "Makefile")'
    required: false
    default: 'Makefile'

runs:
  using: 'composite'
  steps:
    - name: Prepare Environment
      shell: bash
      run: |
        echo "MAKEFILE=${{ inputs.makefile }}" >> $GITHUB_ENV
        echo "COMMAND=${{ inputs.command }}" >> $GITHUB_ENV
    
    - name: Environment Check
      shell: bash
      run: |
        if [ ! -f "$MAKEFILE" ]; then
          echo "$MAKEFILE not found! Exiting. . ."
          exit 1
        fi

    - name: Run Make Command
      shell: bash
      run: make -f "$MAKEFILE" "$COMMAND"